<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\..\abpversion.props"></Import>
  <Import Project="..\..\modulecommon.props"></Import>
  <PropertyGroup>
    <TargetFramework>$(DotNetVersion)</TargetFramework>
    <RootNamespace>Yoyo.LowCode</RootNamespace>
  </PropertyGroup>
  <!-- Yoyo.Pro -->
  <ItemGroup Condition="'$(YoyoProRefMode)'=='nuget'">
    <PackageReference Include="Yoyo.Pro.Identity.Core" Version="$(YoyoProVersion)" />
    <PackageReference Include="Yoyo.Pro.EFCore.BulkExtensions" Version="$(YoyoProVersion)" />
  </ItemGroup>

  <!-- Yoyo.Pro -->
  <ItemGroup Condition="'$(YoyoProRefMode)'=='src'">
    <ProjectReference Include="..\..\..\modules-business\identity\src\Yoyo.Pro.Identity.Core\Yoyo.Pro.Identity.Core.csproj" />
    <ProjectReference Include="..\..\..\modules\Yoyo.Pro.EFCore.BulkExtensions\Yoyo.Pro.EFCore.BulkExtensions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Localization\SourceFiles\YoyoLowCode-zh-Hans.json" />
    <None Remove="Localization\SourceFiles\YoyoLowCode.json" />
  </ItemGroup>
  <ItemGroup>
      <EmbeddedResource Include="Localization\SourceFiles\YoyoLowCode-zh-Hans.json" />
       <EmbeddedResource Include="Localization\SourceFiles\YoyoLowCode.json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Yoyo.LowCode.DbStore\Yoyo.LowCode.DbStore.csproj" />
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties /></VisualStudio></ProjectExtensions>
</Project>
