<Project Sdk="Microsoft.NET.Sdk">  <Import Project="..\..\..\abpversion.props"></Import>  <Import Project="..\modulecommon.props"></Import>  <PropertyGroup>    <TargetFramework>net6.0</TargetFramework>    <RootNamespace>Yoyo.Pro</RootNamespace>    <Nullable>disable</Nullable>  </PropertyGroup>  <ItemGroup>    <PackageReference Include="AlibabaCloud.SDK.Dysmsapi20170525" Version="2.0.23" />    <PackageReference Include="MailKit" Version="3.4.3" />    <PackageReference Include="TencentCloudSDK" Version="3.0.652" />    <PackageReference Include="WebApiClientCore" Version="2.0.3" />  </ItemGroup>  <!-- nuget -->  <ItemGroup Condition="'$(AbpRefMode)'=='nuget'">    <PackageReference Include="Yoyo.Abp" Version="$(AbpVersion)" />  </ItemGroup>  <!-- src -->  <ItemGroup Condition="'$(AbpRefMode)'=='src'">    <ProjectReference Include="..\..\..\..\yoyo.abp\src\Yoyo\Yoyo.csproj" />  </ItemGroup></Project>