<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\abpversion.props"></Import>
  <Import Project="..\modulecommon.props"></Import>

  <PropertyGroup>
    <TargetFramework>$(DotNetVersion)</TargetFramework>
    <RootNamespace>Yoyo.Pro</RootNamespace>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="..\Yoyo.Pro\Yoyo.Pro.csproj" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Yoyo.Abp.AspNetCore" Version="$(AbpVersion)" />
    <PackageReference Include="Yoyo.Abp.ZeroCore.EntityFrameworkCore" Version="$(AbpVersion)" />
  </ItemGroup>

</Project>
