<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\abpversion.props"></Import>
  <Import Project="..\modulecommon.props"></Import>


  <PropertyGroup>
    <TargetFramework>$(DotNetVersion)</TargetFramework>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="EFCore.BulkExtensions" Version="8.0.2" />
    <!--<PackageReference Include="EFCore.BulkExtensions.MySql" Version="8.0.2" />
    <PackageReference Include="EFCore.BulkExtensions.PostgreSql" Version="8.0.2" />
    <PackageReference Include="EFCore.BulkExtensions.Sqlite" Version="8.0.2" />
    <PackageReference Include="EFCore.BulkExtensions.SqlServer" Version="8.0.2" />-->
  </ItemGroup>

</Project>