<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\abpversion.props"></Import>
  <Import Project="..\modulecommon.props"></Import>

  <PropertyGroup>
    <TargetFramework>$(DotNetVersion)</TargetFramework>
    <RootNamespace>Yoyo.Pro</RootNamespace>
    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WorkflowCore" Version="3.6.4" />
    <PackageReference Include="WorkflowCore.DSL" Version="3.6.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yoyo.Pro\Yoyo.Pro.csproj" />
  </ItemGroup>

</Project>
