<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\..\abpversion.props"></Import>
  <Import Project="..\modulecommon.props"></Import>

  <PropertyGroup>
    <TargetFramework>$(Std20)</TargetFramework>
    <RootNamespace>Yoyo.Pro</RootNamespace>


  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="MessagePack" Version="2.5.108" />
    <PackageReference Include="Polly" Version="7.2.3" />
    <PackageReference Include="RabbitMQ.Client" Version="6.5.0" />
  </ItemGroup>
  
  
  <!-- nuget -->
  <ItemGroup Condition="'$(AbpRefMode)'=='nuget'">
    <PackageReference Include="Yoyo.Abp" Version="$(AbpVersion)" />
  </ItemGroup>
  <!-- src -->
  <ItemGroup Condition="'$(AbpRefMode)'=='src'">
    <ProjectReference Include="..\..\..\..\yoyo.abp\src\Yoyo\Yoyo.csproj" />
  </ItemGroup>


</Project>
