<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\abpversion.props"></Import>
  <Import Project="..\modulecommon.props"></Import>

  <PropertyGroup>
    <TargetFramework>$(DotNetVersion)</TargetFramework>
    <RootNamespace>Yoyo.Pro</RootNamespace>
    
    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="aliyun-net-sdk-sts" Version="3.1.0" />
    <PackageReference Include="Aliyun.OSS.SDK.NetCore" Version="2.13.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yoyo.Pro.BlobStoring\Yoyo.Pro.BlobStoring.csproj" />
  </ItemGroup>

</Project>
