<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\abpversion.props"></Import>
  <Import Project="..\modulecommon.props"></Import>

  <PropertyGroup>
    <TargetFramework>$(DotNetVersion)</TargetFramework>
    <RootNamespace>Yoyo.Pro</RootNamespace>
    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Alipay.AopSdk.AspnetCore" Version="2.5.0.1" />
    <PackageReference Include="QRCoder" Version="1.3.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yoyo.Pro\Yoyo.Pro.csproj" />
  </ItemGroup>

</Project>
