<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\abpversion.props"></Import>
  <Import Project="..\modulecommon.props"></Import>
  <PropertyGroup>
    <TargetFramework>$(DotNetVersion)</TargetFramework>
    <RootNamespace>Yoyo.Pro</RootNamespace>
    
    
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Localization\SourceFiles\*.json" Exclude="bin\**;obj\**;**\*.xproj;packages\**;@(EmbeddedResource)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\modules\Yoyo.Pro\Yoyo.Pro.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Castle.Windsor.MsDependencyInjection" Version="3.4.0" />
    <PackageReference Include="Riven.System.Linq.Dynamic.Core.Extensions" Version="0.1.5" />
    <PackageReference Include="Markdig.Signed" Version="0.30.2" />
  </ItemGroup>
  <!-- nuget -->
  <ItemGroup Condition="'$(AbpRefMode)'=='nuget'">
    <PackageReference Include="Yoyo.Abp.ZeroCore" Version="$(AbpVersion)" />
    <PackageReference Include="Yoyo.Abp.ZeroCore.IdentityServer4.EntityFrameworkCore" Version="$(AbpVersion)" />
  </ItemGroup>
  <!-- src -->
  <ItemGroup Condition="'$(AbpRefMode)'=='src'">
   <ProjectReference Include="..\..\..\yoyoboot.abp\src\Abp.ZeroCore\Abp.ZeroCore.csproj" />
   <ProjectReference Include="..\..\..\yoyoboot.abp\src\Abp.ZeroCore.IdentityServer4.EntityFrameworkCore\Abp.ZeroCore.IdentityServer4.EntityFrameworkCore.csproj" />
  </ItemGroup>
</Project>
