
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\abpversion.props"></Import>
  <Import Project="..\modulecommon.props"></Import>

  <PropertyGroup>
    <TargetFramework>$(Std20)</TargetFramework>
    <RootNamespace>Yoyo.Pro</RootNamespace>
    
    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Polly" Version="7.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yoyo.Pro.BlobStoring\Yoyo.Pro.BlobStoring.csproj" />
  </ItemGroup>
</Project>
