<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\abpversion.props"></Import>
  <Import Project="..\modulecommon.props"></Import>

  <PropertyGroup>
    <TargetFramework>$(DotNetVersion)</TargetFramework>
    <RootNamespace>Yoyo.Pro</RootNamespace>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="aliyun-net-sdk-core" Version="1.5.11" />
    <PackageReference Include="aliyun-net-sdk-vod" Version="2.16.9" />
    <PackageReference Include="Aliyun.OSS.SDK.NetCore" Version="2.13.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yoyo.Pro\Yoyo.Pro.csproj" />
  </ItemGroup>


</Project>
