<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\abpversion.props"></Import>
  <Import Project="..\modulecommon.props"></Import>

  <PropertyGroup>
    <TargetFramework>$(DotNetVersion)</TargetFramework>
    <RootNamespace>Yoyo.Pro</RootNamespace>
    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mren.Aliyun" Version="1.0.8" />
    <PackageReference Include="aliyun-net-sdk-core" Version="1.5.11" />
    <PackageReference Include="aliyun-net-sdk-vod" Version="2.16.9" />
    <!--<PackageReference Include="aliyun.oss.sdk.core" Version="2.5.3" />-->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yoyo.Pro\Yoyo.Pro.csproj" />
  </ItemGroup>


</Project>
