<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\abpversion.props"></Import>
  <Import Project="..\modulecommon.props"></Import>

  <PropertyGroup>
    <TargetFramework>$(DotNetVersion)</TargetFramework>
    <RootNamespace>Yoyo.Pro</RootNamespace>
    
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="6.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yoyo.Pro.WorkflowCore\Yoyo.Pro.WorkflowCore.csproj" />
  </ItemGroup>

</Project>
